# **Loan Default Prediction**

### **Introduction**: This project aims to analyze business problems, preprocess data, build machine learning models, and evaluate them for performance and fairness to predict loan default and recommend actions based on your findings.

## **1. Data Analysis and Cleaning**

### **Load and inspect the dataset**

In [3]:
# Import libraries
import pandas as pd

In [ ]:
# Load the dataset

loan_data = pd.read_csv("bank-loan.csv")

loan_data.head()

   age  ed  employ  address  income  debtinc   creddebt   othdebt  default
0   41   3      17       12     176      9.3  11.359392  5.008608      1.0
1   27   1      10        6      31     17.3   1.362202  4.000798      0.0
2   40   1      15       14      55      5.5   0.856075  2.168925      0.0
3   41   1      15       14     120      2.9   2.658720  0.821280      0.0
4   24   2       2        0      28     17.3   1.787436  3.056564      1.0

In [ ]:
# Check the dataset structure and content

loan_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       850 non-null    int64
 1   ed        850 non-null    int64
 2   employ    850 non-null    int64
 3   address   850 non-null    int64
 4   income    850 non-null    int64
 5   debtinc   850 non-null    float64
 6   creddebt  850 non-null    float64
 7   othdebt   850 non-null    float64
 8   default   700 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 59.9 KB

In [7]:
# Identify the missing values

loan_data.isnull().sum()

age           0
ed            0
employ        0
address       0
income        0
debtinc       0
creddebt      0
othdebt       0
default     150
dtype: int64

In [ ]:
# Handle missing values
# Since the missing values are in the target variable, we opt to drop them

loan_data = loan_data.dropna(subset=['default'])

In [11]:
loan_data.isnull().sum()

age         0
ed          0
employ      0
address     0
income      0
debtinc     0
creddebt    0
othdebt     0
default     0
dtype: int64

In [8]:
# Summary statistics

loan_data.describe()

,age,ed,employ,address,income,debtinc,creddebt,othdebt,default
count,850.000000,850.000000,850.000000,850.000000,850.000000,850.000000,850.000000,850.000000,700.000000
mean,35.029412,1.710588,8.565882,8.371765,46.675294,10.171647,1.576805,3.078789,0.261429
std,8.041432,0.927784,6.777884,6.895016,38.543054,6.719441,2.125840,3.398803,0.439727
min,20.000000,1.000000,0.000000,0.000000,13.000000,0.100000,0.011696,0.045584,0.000000
25%,29.000000,1.000000,3.000000,3.000000,24.000000,5.100000,0.382176,1.045942,0.000000
50%,34.000000,1.000000,7.000000,7.000000,35.000000,8.700000,0.885091,2.003243,0.000000
75%,41.000000,2.000000,13.000000,12.000000,55.750000,13.800000,1.898440,3.903001,1.000000
max,56.000000,5.000000,33.000000,34.000000,446.000000,41.300000,20.561310,35.197500,1.000000

In [ ]:
# Check the remaining columns and rows

loan_data.shape

(700, 9)

In [ ]:
# Check the distribution of the target variable 

loan_data['default'].value_counts()

default
0.0    517
1.0    183
Name: count, dtype: int64

In [14]:
# Display in percentage

loan_data['default'].value_counts(normalize=True) * 100

default
0.0    73.857143
1.0    26.142857
Name: proportion, dtype: float64

The above distribution shows imbalance in the outcome variable classes.