# **Assignment 14_Ethical AI Analysis**

## **Fairness and Explainability in Machine Learning for Heart Disease Prediction**

*The objective of this project is to develop a Logistic Regression model to predict heart disease and evaluate its performance, fairness, and explainability. We will use the Heart Disease dataset from UCI repository*

### **1. Data preparation**

In [1]:
# Import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
%pip install ucimlrepo fairlearn shap lime

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Collecting fairlearn
  Downloading fairlearn-0.14.0-py3-none-any.whl.metadata (7.3 kB)
Collecting shap
  Downloading shap-0.52.0-cp312-abi3-win_amd64.whl.metadata (26 kB)
Collecting lime
  Downloading lime-0.2.0.1.tar.gz (275 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: pandas>=1.0.0 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from ucimlrepo) (3.0.5)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from ucimlrepo) (2026.7.22)
Requirement already satisfied: narwhals>=1.14.0 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from fairlearn) (2.22.1)
Requirement already satisfied: numpy>=1.24.4 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from fairlearn) (2.5.2)
Requirement already satisfied: scikit-learn>=1.5.0 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from fairlearn) (1.9.0)
Requirement already satisfied: scipy>=1.9.3 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from fairlearn) (1.18.1)
Requirement already satisfied: tqdm>=4.27.0 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from shap) (4.70.1)
Requirement already satisfied: packaging>20.9 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from shap) (26.2)
Collecting slicer==0.0.8 (from shap)
  Downloading slicer-0.0.8-py3-none-any.whl.metadata (4.0 kB)
Collecting numba (from shap)
  Downloading numba-0.67.0-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Collecting llvmlite (from shap)
  Downloading llvmlite-0.49.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: cloudpickle in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from shap) (3.1.2)
Requirement already satisfied: matplotlib in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from lime) (3.11.1)
Requirement already satisfied: scikit-image>=0.12 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from lime) (0.26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Requirement already satisfied: networkx>=3.0 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-image>=0.12->lime) (3.6.1)
Requirement already satisfied: pillow>=10.1 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-image>=0.12->lime) (12.3.0)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-image>=0.12->lime) (2.37.4)
Requirement already satisfied: tifffile>=2022.8.12 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-image>=0.12->lime) (2026.9.15)
Requirement already satisfied: lazy-loader>=0.4 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-image>=0.12->lime) (0.5)
Requirement already satisfied: joblib>=1.4.0 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn>=1.5.0->fairlearn) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn>=1.5.0->fairlearn) (3.6.0)
Requirement already satisfied: colorama in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from tqdm>=4.27.0->shap) (0.4.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib->lime) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib->lime) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib->lime) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib->lime) (1.5.1)
Requirement already satisfied: pyparsing>=3 in c:\users\yvesa\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib->lime) (3.3.2)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Downloading fairlearn-0.14.0-py3-none-any.whl (135 kB)
Downloading shap-0.52.0-cp312-abi3-win_amd64.whl (499 kB)
Downloading slicer-0.0.8-py3-none-any.whl (15 kB)
Downloading llvmlite-0.49.0-cp314-cp314-win_amd64.whl (43.0 MB)
   ---------------------------------------- 0.0/43.0 MB ? eta -:--:--
   - -------------------------------------- 1.6/43.0 MB 8.7 MB/s eta 0:00:05
   -- ------------------------------------- 3.1/43.0 MB 7.7 MB/s eta 0:00:06
   ---- ----------------------------------- 5.0/43.0 MB 8.4 MB/s eta 0:00:05
   ----- ---------------------------------- 5.8/43.0 MB 7.4 MB/s eta 0:00:06
   ------ --------------------------------- 6.6/43.0 MB 6.6 MB/s eta 0:00:06
   ------- -------------------------------- 8.4/43.0 MB 6.7 MB/s eta 0:00:06
   --------- ------------------------------ 9.7/43.0 MB 6.5 MB/s eta 0:00:06
   ---------- ----------------------------- 11.8/43.0 MB 7.1 MB/s eta 0:00:05
   ------------ --------------------------- 13.6/43.0 MB 7.2 MB/s eta 0:00:05
   --------------- ------------------------ 16.8/43.0 MB 7.9 MB/s eta 0:00:04
   ----------------- ---------------------- 19.1/43.0 MB 8.2 MB/s eta 0:00:03
   ------------------- -------------------- 21.2/43.0 MB 8.3 MB/s eta 0:00:03
   --------------------- ------------------ 23.1/43.0 MB 8.5 MB/s eta 0:00:03
   ---------------------- ----------------- 24.6/43.0 MB 8.4 MB/s eta 0:00:03
   ------------------------ --------------- 26.2/43.0 MB 8.3 MB/s eta 0:00:03
   -------------------------- ------------- 28.0/43.0 MB 8.3 MB/s eta 0:00:02
   --------------------------- ------------ 29.9/43.0 MB 8.3 MB/s eta 0:00:02
   ---------------------------- ----------- 30.9/43.0 MB 8.2 MB/s eta 0:00:02
   ------------------------------ --------- 33.0/43.0 MB 8.2 MB/s eta 0:00:02
   ------------------------------- -------- 34.1/43.0 MB 8.1 MB/s eta 0:00:02
   -------------------------------- ------- 35.4/43.0 MB 7.9 MB/s eta 0:00:01
   ---------------------------------- ----- 37.2/43.0 MB 8.0 MB/s eta 0:00:01
   ------------------------------------ --- 39.6/43.0 MB 8.1 MB/s eta 0:00:01
   ------------------------------------- -- 40.6/43.0 MB 8.0 MB/s eta 0:00:01
   ---------------------------------------  42.2/43.0 MB 8.0 MB/s eta 0:00:01
   ---------------------------------------- 43.0/43.0 MB 7.8 MB/s  0:00:05
Downloading numba-0.67.0-cp314-cp314-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ----------------------------- ---------- 2.1/2.8 MB 12.7 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 10.3 MB/s  0:00:00
Building wheels for collected packages: lime
  Building wheel for lime (pyproject.toml): started
  Building wheel for lime (pyproject.toml): finished with status 'done'
  Created wheel for lime: filename=lime-0.2.0.1-py3-none-any.whl size=284306 sha256=f6a2c9e36b6617e5a096b7396d3732b1777a08b35757d048228b522473c88797
  Stored in directory: c:\users\yvesa\appdata\local\pip\cache\wheels\eb\51\d9\c707b8fa7dee923cf3cb03edaf5c7f2bfeed5b91f5ca72f468
Successfully built lime
Installing collected packages: slicer, llvmlite, numba, ucimlrepo, shap, lime, fairlearn

   ----- ---------------------------------- 1/7 [llvmlite]
   ----- ---------------------------------- 1/7 [llvmlite]
   ----- ---------------------------------- 1/7 [llvmlite]
   ----- ---------------------------------- 1/7 [llvmlite]
   ----- ---------------------------------- 1/7 [llvmlite]
   ----- ---------------------------------- 1/7 [llvmlite]
   ----- ---------------------------------- 1/7 [llvmlite]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ----------- ---------------------------- 2/7 [numba]
   ---------------------- ----------------- 4/7 [shap]
   ---------------------- ----------------- 4/7 [shap]
   ---------------------------- ----------- 5/7 [lime]
   ---------------------------------- ----- 6/7 [fairlearn]
   ---------------------------------------- 7/7 [fairlearn]

Successfully installed fairlearn-0.14.0 lime-0.2.0.1 llvmlite-0.49.0 numba-0.67.0 shap-0.52.0 slicer-0.0.8 ucimlrepo-0.0.7
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
# Load the heart disease dataset

from ucimlrepo import fetch_ucirepo

# Load Heart Disease dataset
heart = fetch_ucirepo(id=45)

# Features and target
X = heart.data.features.copy()
y = heart.data.targets.copy()

In [ ]:
# Show the first 5 rows for the features

X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,1,145,233,1,2,150,0,2.3,3,0.0,6.0
1,67,1,4,160,286,0,2,108,1,1.5,2,3.0,3.0
2,67,1,4,120,229,0,2,129,1,2.6,2,2.0,7.0
3,37,1,3,130,250,0,0,187,0,3.5,3,0.0,3.0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,3.0

In [6]:
# Show the first 5 rows for the target variable

y.head()

   num
0    0
1    2
2    1
3    0
4    0

In [ ]:
# Examine the dataset

X.info()

<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        299 non-null    float64
 12  thal      301 non-null    float64
dtypes: float64(3), int64(10)
memory usage: 30.9 KB

In [9]:
y.value_counts()

num
0      164
1       55
2       36
3       35
4       13
Name: count, dtype: int64